### ISSUE TITLE
How to setup Fuzzmanager with Quokka

### ISSUE THREAD

**Issue by shubham0d** [MozillaSecurity/quokka#13]
I have setup the quokka successfully. 
I have found that fuzzmanager is available inside utils and its running. But I am not able to figure out how to make crash added to fuzzmanager automatically.
Any help would be appreciated.

**Comment by posidron** [comment]
Sorry, Quokka is not official supported anymore and probably won't be in the foreseeable future. There have been made too many changes in FuzzManager in the meantime which make this module obsolete. You can check out https://github.com/MozillaSecurity/grizzly as alternative.

**Comment by posidron** [comment]
Okay, I just noticed that the Grizzly harness is still private. I honestly haven't run Quokka for some time now but I would recommend to follow the setup guidelines here: https://github.com/MozillaSecurity/FuzzManager if you haven't done so yet and make sure the configuration files for FM are in the right place. I.e the configuration file next to the binary as required here: https://github.com/MozillaSecurity/quokka/blob/master/core/loggers/fuzzmanager.py#L55

**Comment by posidron** [comment]
Another alternative would be here: https://github.com/MozillaSecurity/ffpuppet
